//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EMSModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EMSModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS.Entities.EMSModelResources", typeof(EMSModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Account Holder1 Name&apos;..
        /// </summary>
        internal static string AccountHolder1NameIsRequired {
            get {
                return ResourceManager.GetString("AccountHolder1NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Account Holder Name&apos;..
        /// </summary>
        internal static string AccountHolderNameIsRequired {
            get {
                return ResourceManager.GetString("AccountHolderNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Account Number&apos;..
        /// </summary>
        internal static string AccountNumberCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountNumberCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Account Type&apos;..
        /// </summary>
        internal static string AccountTypeIsRequired {
            get {
                return ResourceManager.GetString("AccountTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Asset Name&apos;..
        /// </summary>
        internal static string AssetNameIsRequired {
            get {
                return ResourceManager.GetString("AssetNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Bank Name&apos;..
        /// </summary>
        internal static string BankNameIsRequired {
            get {
                return ResourceManager.GetString("BankNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Business ID&apos;..
        /// </summary>
        internal static string BusinessIDIsRequired {
            get {
                return ResourceManager.GetString("BusinessIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Business Name&apos;..
        /// </summary>
        internal static string BusinessNameIsRequired {
            get {
                return ResourceManager.GetString("BusinessNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Business Phone..
        /// </summary>
        internal static string BusinessPhoneIsRequired {
            get {
                return ResourceManager.GetString("BusinessPhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Card Title&apos;..
        /// </summary>
        internal static string CardTitleIsRequired {
            get {
                return ResourceManager.GetString("CardTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Category&apos;..
        /// </summary>
        internal static string CategoryIsRequired {
            get {
                return ResourceManager.GetString("CategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Category Name&apos;..
        /// </summary>
        internal static string CategoryNameIsRequired {
            get {
                return ResourceManager.GetString("CategoryNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City allows only &apos;Alphabets&apos; and &apos;Numbers&apos;..
        /// </summary>
        internal static string CityAllowsonlyAlphabetsAndNumbers {
            get {
                return ResourceManager.GetString("CityAllowsonlyAlphabetsAndNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Company Name&apos;. .
        /// </summary>
        internal static string CompanyNameisRequired {
            get {
                return ResourceManager.GetString("CompanyNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Cost Price&apos;..
        /// </summary>
        internal static string CostPriceIsRequired {
            get {
                return ResourceManager.GetString("CostPriceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Country Name&apos;..
        /// </summary>
        internal static string CountryIsRequired {
            get {
                return ResourceManager.GetString("CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Current Amount&apos;..
        /// </summary>
        internal static string CurrentAmountIsRequired {
            get {
                return ResourceManager.GetString("CurrentAmountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Employee ID..
        /// </summary>
        internal static string EmployeeIDIsRequired {
            get {
                return ResourceManager.GetString("EmployeeIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Employee Number&apos; already exists..
        /// </summary>
        internal static string EmployeeNumberAlreadyExists {
            get {
                return ResourceManager.GetString("EmployeeNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Account Name&apos;..
        /// </summary>
        internal static string EnterAccountName {
            get {
                return ResourceManager.GetString("EnterAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only Numbers..
        /// </summary>
        internal static string EnterOnlyNumbers {
            get {
                return ResourceManager.GetString("EnterOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid &apos;Fax No&apos;..
        /// </summary>
        internal static string EnterValidFaxNo {
            get {
                return ResourceManager.GetString("EnterValidFaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid input like 0.00..
        /// </summary>
        internal static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Port No..
        /// </summary>
        internal static string EntervalidPortNo {
            get {
                return ResourceManager.GetString("EntervalidPortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid &apos;Routing Number&apos;..
        /// </summary>
        internal static string EnterValidRoutingNumber {
            get {
                return ResourceManager.GetString("EnterValidRoutingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid SMTP Server..
        /// </summary>
        internal static string EntervalidSMTPServer {
            get {
                return ResourceManager.GetString("EntervalidSMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid &apos;WebSite&apos;..
        /// </summary>
        internal static string EnterValidWebSite {
            get {
                return ResourceManager.GetString("EnterValidWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;First Name&apos; already exists..
        /// </summary>
        internal static string FirstNameAlreadyExists {
            get {
                return ResourceManager.GetString("FirstNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;First Name&apos;..
        /// </summary>
        internal static string FirstNameIsRequired {
            get {
                return ResourceManager.GetString("FirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;First Name&apos; &amp; &apos;Last Name&apos; already exists..
        /// </summary>
        internal static string FirstNameLastNameAlreadyExists {
            get {
                return ResourceManager.GetString("FirstNameLastNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenderId is required..
        /// </summary>
        internal static string GenderIdIsRequired {
            get {
                return ResourceManager.GetString("GenderIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Initial Amount&apos;..
        /// </summary>
        internal static string InitialAmountIsRequired {
            get {
                return ResourceManager.GetString("InitialAmountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid &apos;Phone number&apos;..
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Amount&apos;..
        /// </summary>
        internal static string KindlyEnterAmount {
            get {
                return ResourceManager.GetString("KindlyEnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Date&apos;..
        /// </summary>
        internal static string KindlyEnterDate {
            get {
                return ResourceManager.GetString("KindlyEnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Description..
        /// </summary>
        internal static string KindlyEnterDescription {
            get {
                return ResourceManager.GetString("KindlyEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;From Date&apos;..
        /// </summary>
        internal static string KindlyEnterFromDate {
            get {
                return ResourceManager.GetString("KindlyEnterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please  enter &apos;Overtime Hours&apos;..
        /// </summary>
        internal static string KindlyEnterOvertimeHours {
            get {
                return ResourceManager.GetString("KindlyEnterOvertimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Regular Hours&apos;..
        /// </summary>
        internal static string KindlyEnterRegularHours {
            get {
                return ResourceManager.GetString("KindlyEnterRegularHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please  enter &apos;To Date&apos;..
        /// </summary>
        internal static string KindlyEnterToDate {
            get {
                return ResourceManager.GetString("KindlyEnterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Employee Name&apos;..
        /// </summary>
        internal static string KindlyselectEmployee {
            get {
                return ResourceManager.GetString("KindlyselectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please  select &apos;Invoice&apos;..
        /// </summary>
        internal static string KindlySelectInvoice {
            get {
                return ResourceManager.GetString("KindlySelectInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Project&apos;..
        /// </summary>
        internal static string KindlySelectProject {
            get {
                return ResourceManager.GetString("KindlySelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Status&apos;..
        /// </summary>
        internal static string KindlySelectStatus {
            get {
                return ResourceManager.GetString("KindlySelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Type&apos;..
        /// </summary>
        internal static string KindlySelectType {
            get {
                return ResourceManager.GetString("KindlySelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Last Name&apos; already exists..
        /// </summary>
        internal static string LastNameAlreadyExists {
            get {
                return ResourceManager.GetString("LastNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Last Name&apos;..
        /// </summary>
        internal static string LastNameIsRequired {
            get {
                return ResourceManager.GetString("LastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Leave Type&apos;..
        /// </summary>
        internal static string LeaveIDIsRequired {
            get {
                return ResourceManager.GetString("LeaveIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers and special characters are not allowed in the Name..
        /// </summary>
        internal static string NumbersAndSpecialCharactersAreNotAllowedInTheName {
            get {
                return ResourceManager.GetString("NumbersAndSpecialCharactersAreNotAllowedInTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Opening Balance&apos;..
        /// </summary>
        internal static string OpeningBalanceIsRequired {
            get {
                return ResourceManager.GetString("OpeningBalanceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Paid By&apos; is required..
        /// </summary>
        internal static string PaidByIsRequired {
            get {
                return ResourceManager.GetString("PaidByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Paid For&apos; is required..
        /// </summary>
        internal static string PaidForIsRequired {
            get {
                return ResourceManager.GetString("PaidForIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Paid From&apos; is required..
        /// </summary>
        internal static string PaidFromIsRequired {
            get {
                return ResourceManager.GetString("PaidFromIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Paid To Account&apos; is required..
        /// </summary>
        internal static string PaidToAccountIsRequired {
            get {
                return ResourceManager.GetString("PaidToAccountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Captcha&apos;..
        /// </summary>
        internal static string PleaseEnterCaptcha {
            get {
                return ResourceManager.GetString("PleaseEnterCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company Website..
        /// </summary>
        internal static string PleaseEnterCompanyWebsite {
            get {
                return ResourceManager.GetString("PleaseEnterCompanyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Display Name.
        /// </summary>
        internal static string PleaseEnterDisplayName {
            get {
                return ResourceManager.GetString("PleaseEnterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Employee Number&apos;..
        /// </summary>
        internal static string PleaseEnterEmployeeNumber {
            get {
                return ResourceManager.GetString("PleaseEnterEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Port No..
        /// </summary>
        internal static string PleaseEnterPortNo {
            get {
                return ResourceManager.GetString("PleaseEnterPortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter SMTP Server..
        /// </summary>
        internal static string PleaseEnterSMTPServer {
            get {
                return ResourceManager.GetString("PleaseEnterSMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;User Name&apos;..
        /// </summary>
        internal static string PleaseEnterUserName {
            get {
                return ResourceManager.GetString("PleaseEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid &apos;Account Number&apos;..
        /// </summary>
        internal static string PleaseEnterValidAccountNumber {
            get {
                return ResourceManager.GetString("PleaseEnterValidAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid &apos;Email&apos;..
        /// </summary>
        internal static string PleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Product Id..
        /// </summary>
        internal static string PleaseEnterValidProductId {
            get {
                return ResourceManager.GetString("PleaseEnterValidProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Project Id..
        /// </summary>
        internal static string PleaseEnterValidProjectId {
            get {
                return ResourceManager.GetString("PleaseEnterValidProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Service Id..
        /// </summary>
        internal static string PleaseEnterValidServiceId {
            get {
                return ResourceManager.GetString("PleaseEnterValidServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid SwiftCode..
        /// </summary>
        internal static string PleaseEnterValidSwiftCode {
            get {
                return ResourceManager.GetString("PleaseEnterValidSwiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Products Id..
        /// </summary>
        internal static string ProductsIdIsRequired {
            get {
                return ResourceManager.GetString("ProductsIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Project Id..
        /// </summary>
        internal static string ProjectIdIsRequired {
            get {
                return ResourceManager.GetString("ProjectIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Reason&apos;..
        /// </summary>
        internal static string ReasonIDIsRequired {
            get {
                return ResourceManager.GetString("ReasonIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By is required..
        /// </summary>
        internal static string ReceivedByIsRequired {
            get {
                return ResourceManager.GetString("ReceivedByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received From is required..
        /// </summary>
        internal static string ReceivedFromIsRequired {
            get {
                return ResourceManager.GetString("ReceivedFromIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received To is required..
        /// </summary>
        internal static string ReceivedToIsRequired {
            get {
                return ResourceManager.GetString("ReceivedToIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Routing Number&apos;..
        /// </summary>
        internal static string RoutingNumberCannotBeEmpty {
            get {
                return ResourceManager.GetString("RoutingNumberCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Number is not valid..
        /// </summary>
        internal static string RoutingNumberIsNotValid {
            get {
                return ResourceManager.GetString("RoutingNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Id is required..
        /// </summary>
        internal static string ServiceIdIsRequired {
            get {
                return ResourceManager.GetString("ServiceIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid &apos;Social Security Number&apos;..
        /// </summary>
        internal static string SocialSecurityNumberIsNotValid {
            get {
                return ResourceManager.GetString("SocialSecurityNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;State Name&apos;..
        /// </summary>
        internal static string StateIsRequired {
            get {
                return ResourceManager.GetString("StateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Balance&apos; is not in the correct format..
        /// </summary>
        internal static string TheBalanceIsNotInTheCorrectFormat {
            get {
                return ResourceManager.GetString("TheBalanceIsNotInTheCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Title&apos;. .
        /// </summary>
        internal static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &apos;Type of Asset&apos;..
        /// </summary>
        internal static string TypeOfAssetIsRequired {
            get {
                return ResourceManager.GetString("TypeOfAssetIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter &apos;Vendor Name&apos;..
        /// </summary>
        internal static string VendorIsRequired {
            get {
                return ResourceManager.GetString("VendorIsRequired", resourceCulture);
            }
        }
    }
}
